CREATE CACHED TABLE PUBLIC.USER(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    ACCOUNT_ID VARCHAR(155),
    NAME VARCHAR(55),
    TOKEN CHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT
)

